VCS:
  GitHub:
    url: http://github.com
    user: username
    type: git
  GitHubEnterprise:
    url: http://github.example.com
    user: username
    type: git
Application:
  WordPress:
    version: 3.8.1
Plugins:
  open-graph-control:
    src: GitHub
    version: 0.1
    method: zip
Themes:
  custom-theme:
    src: GitHubEnterprise
    version: 4.0
Servers:
  localhost:
    address: 
    wordpress: /wordpress
  build:
    address: 
    wordpress: /path/to/wordpress
